// Static demo data matching the seed script — swap for real Prisma queries once DB is connected

export const mockUser = {
  id: "pm-001",
  fullName: "Sarah Chen",
  email: "pm@cornerstone.demo",
  role: "PROJECT_MANAGER" as const,
  title: "Senior Project Manager",
  avatarUrl: null,
};

export const mockProjects = [
  {
    id: "proj-001",
    projectNumber: "CC-2024-001",
    name: "Riverside Office Complex",
    description: "4-story Class A office building with structured parking. LEED Silver target. 85,000 sq ft total.",
    status: "ACTIVE" as const,
    address: "4200 N Riverside Dr",
    city: "Tempe",
    state: "AZ",
    clientName: "Desert Sun Properties LLC",
    startDate: new Date("2024-03-01"),
    targetEndDate: new Date("2025-06-30"),
    actualEndDate: null,
    budgetTotal: 12_800_000,
    budgetSpent: 9_012_000,
    completionPct: 71,
    managerId: "pm-001",
    manager: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
    _count: { rfis: 3, tasks: 6, dailyLogs: 5 },
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2026-04-28"),
    thumbnailUrl: null,
  },
  {
    id: "proj-002",
    projectNumber: "CC-2024-002",
    name: "Highway 50 Interchange Phase 2",
    description: "ADOT infrastructure contract. Phase 2 covers the northern on/off ramp reconstruction and bridge deck overlay.",
    status: "PLANNING" as const,
    address: "US-50 & McQueen Rd",
    city: "Chandler",
    state: "AZ",
    clientName: "Arizona Dept. of Transportation",
    startDate: new Date("2025-02-01"),
    targetEndDate: new Date("2026-08-31"),
    actualEndDate: null,
    budgetTotal: 8_450_000,
    budgetSpent: 215_000,
    completionPct: 3,
    managerId: "pm-001",
    manager: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
    _count: { rfis: 1, tasks: 2, dailyLogs: 1 },
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2026-04-27"),
    thumbnailUrl: null,
  },
  {
    id: "proj-003",
    projectNumber: "CC-2023-008",
    name: "Lakewood Residential Development",
    description: "24-unit townhome community. All units delivered on schedule. Final punch list cleared October 2024.",
    status: "COMPLETED" as const,
    address: "8800 W Lakewood Blvd",
    city: "Goodyear",
    state: "AZ",
    clientName: "Lakewood Homes Group",
    startDate: new Date("2023-05-15"),
    targetEndDate: new Date("2024-10-31"),
    actualEndDate: new Date("2024-10-22"),
    budgetTotal: 4_200_000,
    budgetSpent: 4_088_000,
    completionPct: 100,
    managerId: "pm-001",
    manager: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
    _count: { rfis: 0, tasks: 0, dailyLogs: 0 },
    createdAt: new Date("2023-05-01"),
    updatedAt: new Date("2024-10-22"),
    thumbnailUrl: null,
  },
  {
    id: "proj-004",
    projectNumber: "CC-2024-003",
    name: "Mesa Medical Center Expansion",
    description: "Hospital wing addition — 32,000 sq ft. Project on hold pending permit re-submission after AHJ review comments.",
    status: "ON_HOLD" as const,
    address: "1900 E Main St",
    city: "Mesa",
    state: "AZ",
    clientName: "Banner Health Systems",
    startDate: new Date("2024-09-01"),
    targetEndDate: new Date("2025-12-31"),
    actualEndDate: null,
    budgetTotal: 6_100_000,
    budgetSpent: 340_000,
    completionPct: 6,
    managerId: "pm-001",
    manager: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
    _count: { rfis: 0, tasks: 0, dailyLogs: 0 },
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2026-02-10"),
    thumbnailUrl: null,
  },
];

export const mockStats = {
  activeProjects: 2,
  totalBudget: 21_250_000,
  openRFIs: 4,
  overdueTasks: 2,
};

export const mockRiversideRFIs = [
  {
    id: "rfi-001",
    projectId: "proj-001",
    rfiNumber: 1,
    title: "Structural Steel Beam Dimension Conflict at Grid D-7",
    description: "Per structural drawings S3.2, W18x40 beam at Grid D-7 conflicts with mechanical duct routing shown on M2.1. Beam flange sits 3\" above bottom of duct required clearance.",
    status: "ANSWERED" as const,
    priority: "HIGH" as const,
    submittedById: "field-001",
    assignedToId: "pm-001",
    dueDate: new Date("2026-03-15"),
    answeredAt: new Date("2026-03-14"),
    answer: "Structural engineer confirms beam can be revised to W16x40 with no change to load capacity. Updated sheet S3.2 Rev B attached.",
    attachments: [],
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-03-14"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "rfi-002",
    projectId: "proj-001",
    rfiNumber: 2,
    title: "Fire Sprinkler Head Clearance in Parking Structure",
    description: "Parking deck soffit height at P1-Level is 7'-2\". FP drawings show pendent sprinklers requiring 7'-6\" clearance per NFPA 13.",
    status: "ANSWERED" as const,
    priority: "URGENT" as const,
    submittedById: "field-001",
    assignedToId: "pm-001",
    dueDate: new Date("2026-03-20"),
    answeredAt: new Date("2026-03-18"),
    answer: "Use concealed pendant sprinklers per Tyco TY-FRB series. These require only 1\" clearance below deflector.",
    attachments: [],
    createdAt: new Date("2026-03-16"),
    updatedAt: new Date("2026-03-18"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "rfi-003",
    projectId: "proj-001",
    rfiNumber: 3,
    title: "Exterior Curtainwall Sealant Specification Conflict",
    description: "Spec Section 079200 calls for Dow 795 silicone at curtainwall joints. Curtainwall subcontractor states Dow 795 is incompatible with their framing system finish.",
    status: "OPEN" as const,
    priority: "HIGH" as const,
    submittedById: "field-001",
    assignedToId: "pm-001",
    dueDate: new Date("2026-04-30"),
    answeredAt: null,
    answer: null,
    attachments: [],
    createdAt: new Date("2026-04-18"),
    updatedAt: new Date("2026-04-18"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "rfi-004",
    projectId: "proj-001",
    rfiNumber: 4,
    title: "Elevator Pit Waterproofing — Missing Detail",
    description: "Architectural drawings A5.1 do not include a waterproofing detail for the elevator pit. The pit extends 6'-0\" below grade.",
    status: "IN_REVIEW" as const,
    priority: "MEDIUM" as const,
    submittedById: "field-001",
    assignedToId: "pm-001",
    dueDate: new Date("2026-05-05"),
    answeredAt: null,
    answer: null,
    attachments: [],
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-04-20"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "rfi-005",
    projectId: "proj-001",
    rfiNumber: 5,
    title: "Electrical Panel Room Door Hardware — Code Conflict",
    description: "Electrical room door hardware per door schedule requires card reader access. NEC 110.26 requires electrical rooms to swing out and be openable from inside without a key.",
    status: "OPEN" as const,
    priority: "MEDIUM" as const,
    submittedById: "pm-001",
    assignedToId: "pm-001",
    dueDate: new Date("2026-05-08"),
    answeredAt: null,
    answer: null,
    attachments: [],
    createdAt: new Date("2026-04-22"),
    updatedAt: new Date("2026-04-22"),
    submittedBy: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
];

export const mockRiversideTasks = [
  {
    id: "task-001",
    projectId: "proj-001",
    title: "Submit final MEP coordination drawings to city",
    description: null,
    status: "IN_PROGRESS" as const,
    priority: "HIGH" as const,
    assignedToId: "pm-001",
    dueDate: new Date("2026-05-02"),
    completedAt: null,
    sortOrder: 1,
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-04-28"),
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "task-002",
    projectId: "proj-001",
    title: "Schedule Level 4 concrete pour — confirm mix design",
    description: null,
    status: "TODO" as const,
    priority: "HIGH" as const,
    assignedToId: "field-001",
    dueDate: new Date("2026-05-01"),
    completedAt: null,
    sortOrder: 2,
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-04-28"),
    assignedTo: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
  },
  {
    id: "task-003",
    projectId: "proj-001",
    title: "Owner punch list review — 14 items from April 22 walkthrough",
    description: null,
    status: "IN_PROGRESS" as const,
    priority: "MEDIUM" as const,
    assignedToId: "pm-001",
    dueDate: new Date("2026-05-10"),
    completedAt: null,
    sortOrder: 3,
    createdAt: new Date("2026-04-22"),
    updatedAt: new Date("2026-04-28"),
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "task-004",
    projectId: "proj-001",
    title: "Resolve curtainwall sealant RFI-003 with architect",
    description: null,
    status: "TODO" as const,
    priority: "HIGH" as const,
    assignedToId: "pm-001",
    dueDate: new Date("2026-04-30"),
    completedAt: null,
    sortOrder: 4,
    createdAt: new Date("2026-04-18"),
    updatedAt: new Date("2026-04-28"),
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "task-005",
    projectId: "proj-001",
    title: "Update schedule — incorporate crane delay from April 24",
    description: null,
    status: "DONE" as const,
    priority: "LOW" as const,
    assignedToId: "pm-001",
    dueDate: null,
    completedAt: new Date("2026-04-25"),
    sortOrder: 5,
    createdAt: new Date("2026-04-24"),
    updatedAt: new Date("2026-04-25"),
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
  {
    id: "task-006",
    projectId: "proj-001",
    title: "Confirm roofing warranty documentation from subcontractor",
    description: null,
    status: "TODO" as const,
    priority: "LOW" as const,
    assignedToId: "pm-001",
    dueDate: new Date("2026-05-15"),
    completedAt: null,
    sortOrder: 6,
    createdAt: new Date("2026-04-21"),
    updatedAt: new Date("2026-04-28"),
    assignedTo: { id: "pm-001", fullName: "Sarah Chen", avatarUrl: null },
  },
];

export const mockRiversideLogs = [
  {
    id: "log-001",
    projectId: "proj-001",
    submittedById: "field-001",
    logDate: new Date("2026-04-28"),
    weatherConditions: "Sunny",
    temperatureF: 91,
    workPerformed: "Completed drywall installation on floors 2 and 3, east wing. MEP rough-in inspection passed on Level 2. Elevator shaft formwork set for Level 4 pour scheduled Thursday.",
    crewCount: 34,
    hoursWorked: 8.5,
    safetyNotes: "All crew in PPE. Ladder inspection conducted at 7am.",
    issues: null,
    photos: [],
    createdAt: new Date("2026-04-28"),
    updatedAt: new Date("2026-04-28"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
  },
  {
    id: "log-002",
    projectId: "proj-001",
    submittedById: "field-001",
    logDate: new Date("2026-04-25"),
    weatherConditions: "Partly Cloudy",
    temperatureF: 87,
    workPerformed: "Exterior glazing install progressing — 60% complete on south facade. Concrete pour Level 4 slab, 420 CY placed. Mechanical room rough-in 90% complete.",
    crewCount: 41,
    hoursWorked: 9,
    safetyNotes: "Crane pre-shift inspection completed. No incidents.",
    issues: null,
    photos: [],
    createdAt: new Date("2026-04-25"),
    updatedAt: new Date("2026-04-25"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
  },
  {
    id: "log-003",
    projectId: "proj-001",
    submittedById: "field-001",
    logDate: new Date("2026-04-24"),
    weatherConditions: "Windy",
    temperatureF: 83,
    workPerformed: "Suspended crane operations 11am–2pm due to wind gusts exceeding 25mph. Crew reassigned to interior framing. Level 3 HVAC ductwork installation resumed afternoon.",
    crewCount: 38,
    hoursWorked: 7,
    safetyNotes: "Wind hold protocol followed per safety plan. Documented in incident log.",
    issues: "Crane downtime caused 3-hour delay on Level 4 steel delivery staging.",
    photos: [],
    createdAt: new Date("2026-04-24"),
    updatedAt: new Date("2026-04-24"),
    submittedBy: { id: "field-001", fullName: "Diego Ramirez", avatarUrl: null },
  },
];

export const mockFinancials = [
  { category: "LABOR", budgeted: 3_200_000, actual: 2_890_000 },
  { category: "MATERIALS", budgeted: 4_100_000, actual: 3_640_000 },
  { category: "SUBCONTRACTOR", budgeted: 3_800_000, actual: 2_982_000 },
  { category: "EQUIPMENT", budgeted: 800_000, actual: 312_000 },
  { category: "OVERHEAD", budgeted: 900_000, actual: 188_000 },
];
